trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Angular App
  jobs:
  - job: Build
    displayName: Build
    steps:
    # Install Node JS
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    # Install Angular CLI and dependencies
    - script: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      displayName: 'npm install and build'
    # Copy dist folder
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'dist/angular-starter'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # Publish Build as artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'angular-app'
        publishLocation: 'Container'
- stage: Deploy
  dependsOn: Build
  displayName: Deploy to Storage Account
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'
    # List files
    - script: |
        pwd
        dir $(System.ArtifactsDirectory)
      displayName: List directory's files
    # Delete Resources in Storage Account
    - task: AzureCLI@2
      displayName: 'Delete Resources'
      inputs:
        azureSubscription: 'angular-storage-account-contributor'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: 'az storage blob delete-batch --source \$web --account-name angulartest01 --pattern ''[!backoffice]*'' --auth-mode login'
    # Delete Resources in Storage Account
    - task: AzureCLI@2
      displayName: 'Copy Resources'
      inputs:
        azureSubscription: 'angular-storage-account-contributor'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: 'az storage blob upload-batch -s "$(System.DefaultWorkingDirectory)/_gustavo-fernandez.angular-example-routing/angular-app" -d \$"web" --account-name angulartest01'