# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    dir
  displayName: 'npm install and build'

- script: |
    cd
    dir
  displayName: 'cd and dir'

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'dist/*'
    azureSubscription: 'Azure Pass - Sponsorship(09bcda39-d435-4e13-b048-5294a566503d)'
    Destination: 'AzureBlob'
    storage: 'storageaccount20201016'
    ContainerName: '$web'
    BlobPrefix: 'prueba'
